// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:boorusama/core/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BlacklistedTagHiveObjectAdapter());
    registerAdapter(BookmarkGroupHiveObjectAdapter());
    registerAdapter(BookmarkGroupMembershipHiveObjectAdapter());
    registerAdapter(BookmarkHiveObjectAdapter());
    registerAdapter(FavoriteTagHiveObjectAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BlacklistedTagHiveObjectAdapter());
    registerAdapter(BookmarkGroupHiveObjectAdapter());
    registerAdapter(BookmarkGroupMembershipHiveObjectAdapter());
    registerAdapter(BookmarkHiveObjectAdapter());
    registerAdapter(FavoriteTagHiveObjectAdapter());
  }
}
