include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: error
    parameter_assignments: error
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

formatter:
  trailing_commas: preserve
